export const LOAD_TRAINS_REQUEST = 'LOAD_TRAINS_REQUEST';
export const LOAD_TRAINS_SUCCESS = 'LOAD_TRAINS_SUCCESS';
export const LOAD_TRAINS_FAIL = 'LOAD_TRAINS_FAIL';
export const LOAD_TRAIN_DETAILS_REQUEST = 'LOAD_TRAIN_DETAILS_REQUEST';
export const LOAD_TRAIN_DETAILS_SUCCESS = 'LOAD_TRAIN_DETAILS_SUCCESS';
export const LOAD_TRAIN_DETAILS_FAIL = 'LOAD_TRAIN_DETAILS_FAIL';
